import { execFileSync } from "node:child_process";
import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, resolve, join } from "node:path";
import { personalCaretArgv } from "./lib/personal-argv.ts";

const root = resolve(import.meta.dir, "..");
const portable = process.argv.includes("--portable") || process.argv.includes("--package");
if (portable) execFileSync(process.execPath, [join(root, "scripts/prepare-omp-runtime.ts"), "--standalone"], { cwd: root, stdio: "inherit" });
if (process.argv.includes("--runtime")) execFileSync(process.execPath, [join(root, "scripts/prepare-omp-runtime.ts")], { cwd: root, stdio: "inherit" });
const dist = join(root, "dist");
await mkdir(dist, { recursive: true });
for (const [entrypoint, output] of [["apps/host/src/cli.ts", "host/cli.js"], ["apps/host/src/runtime-lock.ts", "host/runtime-lock.ts"]]) {
  const result = await Bun.build({ entrypoints: [join(root, entrypoint!)], outdir: join(dist, "host"), target: "node", format: "esm", naming: output!.split("/").at(-1)!, sourcemap: "external" });
  if (!result.success) throw new AggregateError(result.logs, `Build failed: ${entrypoint}`);
}
const extensionOutput = join(dist, "mac-extension");
await mkdir(extensionOutput, { recursive: true });
const extension = await Bun.build({ entrypoints: [join(root, "apps/macos/src/extension.ts")], outdir: join(extensionOutput, "out"), target: "node", format: "cjs", external: ["vscode"], naming: "extension.js", sourcemap: "external" });
if (!extension.success) throw new AggregateError(extension.logs, "Mac extension build failed");
const manifest = JSON.parse(await readFile(join(root, "apps/macos/package.json"), "utf8"));
delete manifest.type; manifest.name = "caret"; manifest.publisher = "caret";
manifest.contributes.configuration.properties["caret.hostNodePath"].default = portable ? "" : process.env.CARET_HOST_NODE ?? process.execPath;
manifest.contributes.configuration.properties["caret.hostScriptPath"].default = portable ? "" : join(dist, "host", "cli.js");
await writeFile(join(extensionOutput, "package.json"), JSON.stringify(manifest, null, 2) + "\n");
await cp(join(root, "apps/macos/media"), join(extensionOutput, "media"), { recursive: true });
if (portable) {
  const node = process.env.CARET_HOST_NODE;
  if (!node) throw new Error("Set CARET_HOST_NODE to the Node 24 executable to bundle");
  const version = execFileSync(node, ["--version"], { encoding: "utf8" }).trim();
  if (!/^v24\./.test(version)) throw new Error("Caret host bundle requires Node 24");
  const runtime = join(extensionOutput, "runtime");
  await mkdir(join(runtime, "node/bin"), { recursive: true });
  await cp(node, join(runtime, "node/bin/node"));
  await cp(join(dirname(node), "../LICENSE"), join(runtime, "node/LICENSE"));
  await cp(join(dist, "host"), join(runtime, "host"), { recursive: true });
  await writeFile(join(runtime, "host/package.json"), JSON.stringify({ private: true, type: "module" }) + "\n");
  await mkdir(join(runtime, "omp"), { recursive: true });
  await cp(join(dist, "omp-standalone/omp"), join(runtime, "omp/omp"));
  await cp(join(root, "upstream/omp/LICENSE"), join(runtime, "omp/LICENSE"));
  // Build evidence is kept outside the runnable payload: it contains source paths.
  await cp(join(root, "docs/upstream-notices"), join(runtime, "notices"), { recursive: true });
}
// Code-OSS Electron packaging and the DMG builder both consume this icon.
const brandIcon = join(root, "assets/brand/insert-v1/caret.icns");
await mkdir(join(dist, "brand"), { recursive: true });
await cp(brandIcon, join(dist, "brand/caret.icns"));
if (process.argv.includes("--desktop")) {
  execFileSync(process.execPath, [join(root, "scripts/prepare-desktop.ts")], { cwd: root, stdio: "inherit" });
  // The retained, ignored Code-OSS checkout is a build output. Tracked source stays above.
  await cp(extensionOutput, join(root, "desktop/extensions/caret"), { recursive: true });
  await cp(brandIcon, join(root, "desktop/resources/darwin/code.icns"));
  await writeFile(join(root, "desktop/argv.json"), JSON.stringify(personalCaretArgv(), null, 2) + "\n");
}
if (process.argv.includes("--package")) {
  const app = join(root, `VSCode-darwin-${process.arch}`, "Caret.app");
  const appExtension = join(app, "Contents/Resources/app/extensions/caret");
  // This target is generated by the pinned Code-OSS packaging task.
  await readFile(join(app, "Contents/Info.plist"));
  await rm(appExtension, { recursive: true, force: true });
  await cp(extensionOutput, appExtension, { recursive: true });
  // Tree-sitter opens WASM by a real node_modules path, outside Electron ASAR
  // resolution. Reuse the exact filtered assets emitted by the pinned packager.
  const appResources = join(app, "Contents/Resources/app");
  await cp(join(appResources, "node_modules.asar.unpacked/@vscode/tree-sitter-wasm"),
    join(appResources, "node_modules/@vscode/tree-sitter-wasm"), { recursive: true });
  // Product decision 2026-09-13: single agent surface. Remove the bundled
  // Copilot Chat agent UI (ships in the `copilot` dir) so it cannot front its
  // own Sessions/Chats over the Caret shell. OMP stays the only harness.
  // `github`/`github-authentication` stay: unrelated to the agent UI.
  // Re-apply on every --package: the pinned Code-OSS packager restores it.
  await rm(join(appResources, "extensions/copilot"), { recursive: true, force: true });
  await writeFile(join(app, "Contents/Resources/app/argv.json"), JSON.stringify(personalCaretArgv(), null, 2) + "\n");
  execFileSync("codesign", ["--force", "--deep", "--sign", "-", app], { stdio: "inherit" });
  execFileSync("codesign", ["--verify", "--deep", "--strict", app], { stdio: "inherit" });
  console.log(`Prepared local ad-hoc signed app (not notarized): ${app}`);
}
console.log(`Built Caret host and Mac extension in ${dist}`);
